echo "<!DOCTYPE HTML>\n";
echo "<html lang=\"en\">\n";
echo "    <head>\n";
echo "        <meta charset=\"utf-8\">\n";
echo "        <title>FACEBOOK HOME PAGE</title>\n";
echo "    </head>\n";
echo "    \n";
echo "    <body bgcolor=\"black\">\n";
echo "        <!--MAIN TABLE-->\n";
echo "        <table bgcolor=\"white\" align=\"center\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n";
echo "            <tr>\n";
echo "                <td>\n";
echo "                    \n";
echo "                    <!--ROW 1-->\n";
echo "                    <table bgcolor=\"#3B5998\" align=\"center\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n";
echo "                        <tr height=\"100\" align=\"center\">\n";
echo "                            <td>\n";
echo "                                <table bgcolor=\"#3B5998\" align=\"center\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n";
echo "                                    <tr>\n";
echo "                                        <!-- FACEBOOK -->\n";
echo "                                        <td align=\"left\" width=\"50%\"><h1><font face=\"helvetica\" color=\"white\" size=\"20\">         facebook</font></h1></td>\n";
echo "                                        \n";
echo "                                        <!-- datainput field-->\n";
echo "                                        <td align=\"center\" width=\"50%\">\n";
echo "                                            <form action=\"\">\n";
echo "                                                <table bgcolor=\"#3B5998\">\n";
echo "                                                    <!-- Section 1 -->\n";
echo "                                                    <tr>\n";
echo "                                                        <td colspan=\"3\"> </td>\n";
echo "                                                    </tr>\n";
echo "                                                    <tr>\n";
echo "                                                     <td>  \n";
echo "                                                        <label for=\"EMAIL\"><font face=\"helvetica\" color=\"white\" size=\"2\">Email or phone</font></label>\n";
echo "                                                        <br>\n";
echo "                                                        <input type=\"text\" placeholder=\"\" size=\"30\" name=\"EMAIL\" id=\"EMAIL\">\n";
echo "                                                     </td>\n";
echo "                                                     \n";
echo "                                                     <td>\n";
echo "                                                        <label for=\"Pass\"><font face=\"helvetica\" color=\"white\" size=\"2\">Password</font></label>\n";
echo "                                                        <br>\n";
echo "                                                        <input type=\"text\" placeholder=\"\" size=\"30\" name=\"Pass\" id=\"Pass\">                                              \n";
echo "                                                     </td>\n";
echo "                                                    \n";
echo "                                                     <!-- LOG IN BUTTON -->\n";
echo "                                                     <td>\n";
echo "                                                        <label for=\"\"></label>\n";
echo "                                                        <br>\n";
echo "                                                        <input type=\"submit\" value=\"Log In\">\n";
echo "                                                     </td>    \n";
echo "                                                    </tr>\n";
echo "                                                    \n";
echo "                                                    <tr>\n";
echo "                                                        <td> </td>\n";
echo "                                                        <td align=\"left\"><h4><font face=\"helvetica\" size=\"2\"><a href=\"#\">forgotten account?</a></font></h4></td>\n";
echo "                                                    </tr>\n";
echo "                                                </table>\n";
echo "                                            </form>\n";
echo "                                        </td>\n";
echo "                                    </tr>\n";
echo "                                </table>\n";
echo "                            </td>\n";
echo "                        </tr>\n";
echo "                    </table>\n";
echo "                    \n";
echo "                    <!--ROW 2-->\n";
echo "                    <table bgcolor=\"#DEE2EE\" align=\"center\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n";
echo "                        <tr height=\"600\" align=\"center\">\n";
echo "                            <!-- ROW 2 COLUMN 1-->\n";
echo "                            <td width=\"50%\">    \n";
echo "                               <table bgcolor=\"#DEE2EE\" align=\"center\" height=\"100%\" width=\"100%\" cellpadding=\"0\" cellspacing=\"50\">\n";
echo "                                   <tr>\n";
echo "                                        <td align=\"center\" width=\"30%\" bgcolor=\"#DEE2EE\"></td> \n";
echo "                                       \n";
echo "                                       <!-- image and writing -->\n";
echo "                                       <td align=\"center\"><font face=\"helvetica\" color=\"#0E385F\"><b><h3>Facebook helps you connect and share with people in your life</h3></b></font>\n";
echo "                                       <br><br>\n";
echo "                                        <img src=\"images/fb_cover_image.png\" align=\"center\">   \n";
echo "                                       \n";
echo "                                       </td>\n";
echo "                                   </tr>\n";
echo "                                   \n";
echo "                                   <tr height=\"50%\"><td></td></tr>\n";
echo "                                </table>\n";
echo "                            </td>\n";
echo "                            \n";
echo "                            <!-- ROW 2 COLUMN 2-->\n";
echo "                            <td width=\"50%\">\n";
echo "                                \n";
echo "                                <h1 align=\"left\"><font face=\"helvetica\" color=\"#333333\">Create An Account</font></h1>\n";
echo "                                <h3 align=\"left\"><font face=\"helvetica\" color=\"#333333\">It's free and always will be!</font>\n";
echo "                                <br><br>\n";
echo "                                    <!--input data field-->\n";
echo "                                <form action=\"\">\n";
echo "                                    <table bgcolor=\"#DEE2EE\" align=\"left\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\n";
echo "                                     <tr>\n";
echo "                                        <td>\n";
echo "                                            <label for=\"Fname\"></label><input type=\"text\" size=\"25\" placeholder=\"First name\"  name=\"Fname\" id=\"Fname\">\n";
echo "                                            \n";
echo "                                            <label for=\"Sname\"></label><input type=\"text\" size=\"25\" placeholder=\"Surname\"  name=\"Sname\" id=\"Sname\">\n";
echo "                                            <br><br>\n";
echo "                                            \n";
echo "                                            <label for=\"email\"></label><input type=\"email\" size=\"55\" placeholder=\"email address\"  name=\"email\" id=\"email\">\n";
echo "                                            <br><br>\n";
echo "                                            \n";
echo "                                            <label for=\"pass\"></label><input type=\"text\" size=\"55\" placeholder=\"New password\"  name=\"pass\" id=\"pass\">\n";
echo "                                            <br><br>\n";
echo "                                            \n";
echo "                                            <label for=\"MOBILE\"></label><input type=\"number\" size=\"25\" placeholder=\"mobile number\"  name=\"MOBILE\" id=\"MOBILE\">\n";
echo "                                            <br>\n";
echo "                                            \n";
echo "                                            <h5><font face=\"helvetica\" color=\"#90949C\"><b>Birthday</b></font></h5>\n";
echo "                                            <label for=\"\">\n";
echo "                                                <select name=\"\" id=\"\">\n";
echo "                                                    <option>--  DAY  --</option>\n";
echo "                                                    <option value=\"1\">1</option>\n";
echo "                                                    <option value=\"1\">2</option>\n";
echo "                                                    <option value=\"1\">3</option>\n";
echo "                                                    <option value=\"1\">4</option>\n";
echo "                                                    <option value=\"1\">5</option>\n";
echo "                                                </select>\n";
echo "                                                \n";
echo "                                                <select name=\"\" id=\"\">\n";
echo "                                                    <option>--  MONTH  --</option>\n";
echo "                                                    <option value=\"1\">1</option>\n";
echo "                                                    <option value=\"1\">2</option>\n";
echo "                                                    <option value=\"1\">3</option>\n";
echo "                                                    <option value=\"1\">4</option>\n";
echo "                                                    <option value=\"1\">5</option>\n";
echo "                                                </select>\n";
echo "                                                <select name=\"\" id=\"\">\n";
echo "                                                    <option>--  YEAR  --</option>\n";
echo "                                                    <option value=\"1\">1</option>\n";
echo "                                                    <option value=\"1\">2</option>\n";
echo "                                                    <option value=\"1\">3</option>\n";
echo "                                                    <option value=\"1\">4</option>\n";
echo "                                                    <option value=\"1\">5</option>\n";
echo "                                                </select>\n";
echo "                                            </label>\n";
echo "                                            <br>\n";
echo "                                            <h5><font face=\"helvetica\" color=\"#90949C\"><b>Gender</b></font></h5>\n";
echo "                                            \n";
echo "                                            <input type=\"radio\" name=\"gender\"><label for=\"\"><font face=\"helvetica\" color=\"#333333\">Female</font></label>\n";
echo "                                            <input type=\"radio\" name=\"gender\"><label for=\"\"><font face=\"helvetica\" color=\"#333333\">Male</font></label>\n";
echo "                                            <input type=\"radio\" name=\"gender\"><label for=\"\"><font face=\"helvetica\" color=\"#333333\">Custom</font></label>\n";
echo "                                            <br>\n";
echo "                                            \n";
echo "                                            <h6><font face=\"helvetica\" color=\"#333333\">By clicking Sign Up, you agree to our <a href=\"#\">Terms</a>, <a href=\"#\">Data Policy</a> and Cookie Policy.<br> You may receive SMS notifications from us and can opt out at any time.</font></h6>\n";
echo "                                            <br>\n";
echo "                                            \n";
echo "                                            <input type=\"submit\" value=\"Sign Up\">\n";
echo "                                            <br>\n";
echo "                                            \n";
echo "                                            <h6><font face=\"helvetica\" color=\"#333333\"><a href=\"#\">Create a Page</a> for a celebrity, band or business.</font></h6>\n";
echo "                                        </td>\n";
echo "                                     </tr> \n";
echo "                                    </table>\n";
echo "                                </form>\n";
echo "                            </td>\n";
echo "                        </tr>\n";
echo "                    </table>\n";
echo "                    \n";
echo "                    \n";
echo "                    <!-- ROW 3-->\n";
echo "                    <table bgcolor=\"white\" align=\"center\" width=\"75%\" cellpadding=\"0\" cellspacing=\"0\">\n";
echo "                        <tr height=\"200\" align=\"center\">\n";
echo "                            <td>\n";
echo "                                <table bgcolor=\"white\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n";
echo "                                    <tr>\n";
echo "                                        <td align=\"left\">\n";
echo "                                            <a href=\"#\">English (UK)</a> <a href=\"#\">বাংলা</a> <a href=\"#\">অসমীয়া</a> <a href=\"#\">हिन्दी</a>  <a href=\"#\">नेपाली</a> <a href=\"#\">Bahasa Indonesia</a> <a href=\"#\">中文(简体)Bahasa Melayu Español Português (Brasil)</a>\n";
echo "                                            \n";
echo "                                            <hr>\n";
echo "                                            \n";
echo "                                            <a href>Sign UpLog InMessengerFacebook Lite Watch People Profiles Pages Page    categories Events Places Games Locations Marketplace Groups Instagram Local Fundraisers Services About Create adCreate Page Developers Careers Privacy Cookies AdChoices \n";
echo "                                            Terms Account security Login help Help\n";
echo "                                            Settings</a>\n";
echo "                                            <br><br>\n";
echo "                                            \n";
echo "                                            <h5><font face=\"helvetica\" color=\"#90949C\">Facebook © 2019</font></h5>\n";
echo "                                            \n";
echo "                                        </td>\n";
echo "                                    </tr>\n";
echo "                                </table>\n";
echo "                            </td>\n";
echo "                        </tr>\n";
echo "                    </table>\n";
echo "                </td>\n";
echo "            </tr>\n";
echo "        </table>\n";
echo "    </body>\n";
echo "</html>";